### ISSUE TITLE
[Abstract Interpretation] Support Class-Based Visitor Interface

### ISSUE THREAD

**Issue by EagleoutIce** [flowr-analysis/flowr#1153]
Provide the [visitor implementation](https://github.com/flowr-analysis/flowr/blob/main/src/r-bridge/lang-4.x/ast/model/processing/visitor.ts) in the commonly known format (`accept(Visitor v)`).

**Comment by gigalasr** [comment]
- [ ] Append to wiki https://github.com/flowr-analysis/flowr/wiki/Normalized-AST
  - [ ] Working with the Normalized AST -> Visiting
