### ISSUE TITLE
Publish nightly releases to npm

### ISSUE THREAD

**Issue by Ellpeck** [flowr-analysis/flowr#778]
This would allow us to update the modules, as well as the vscode extension, immediately, rather than having to wait for a release.

Could potentially use GitHub's own NPM registry.

**Comment by EagleoutIce** [comment]
With #784, this has a slightly lower priority.

**Comment by Ellpeck** [comment]
- release on push to main
- publish on regular npm
- name it something like `flowr-dev@commit-id`
