### ISSUE TITLE
Add additional "get_origin" command

### ISSUE THREAD

**Issue by LukasPietzschmann** [flowr-analysis/flowr#903]
The new command requires the ID of a variable and will provide the ID of its origin.
Imagine the following code:
```r
c <- x
b <- c
a <- b
```
and the following request:
```
:get_origin <id of a>
```
This will result in `<id of x>`

Basically, we just walk def edged in the dfg and return the node where we and up.

---

I'm open for better names for the command :)

**Comment by EagleoutIce** [comment]
Besides the REPL request, we want a network message :D
Maybe `getRootDefinitions`?

**Comment by EagleoutIce** [comment]
Theoretically, this can use the current function call resolution, which should handle cases like the following too:

```R
c <- function() { x }
b <- function() { if(TRUE) c() }
a <- b()
```
